<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * GDPR Step 2.2 — user-requested data export. One row per request;
     * rate-limited to 1 per user per 30 days at the controller layer.
     * The ZIP file is generated by DataExportService and stored under
     * `storage/app/data-exports/` with a signed download URL valid for
     * 7 days from `ready_at`.
     */
    public function up(): void
    {
        if (Schema::hasTable('data_export_requests')) {
            return;
        }

        Schema::create('data_export_requests', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->constrained('users')->cascadeOnDelete();
            $table->enum('status', ['pending', 'generating', 'ready', 'failed', 'expired'])->default('pending');
            $table->string('download_token', 96)->nullable()->unique();
            $table->unsignedBigInteger('file_size_bytes')->nullable();
            $table->string('file_path', 512)->nullable();
            $table->timestamp('ready_at')->nullable();
            $table->timestamp('expires_at')->nullable();
            $table->timestamp('downloaded_at')->nullable();
            $table->string('failure_reason', 512)->nullable();
            $table->timestamps();

            $table->index(['user_id', 'status']);
            $table->index('expires_at');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('data_export_requests');
    }
};
